### ISSUE TITLE
Spell Checker Problems

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#390]
I believe this behavior has always existed but I tested it with 0.8.1 AND with the current [basic demo](http://prosemirror.net/demo/basic.html). I've also tested the behavior on a regular contenteditable div (not ProseMirror) and it seems to work correctly.

In Chrome:
1. Underlines show up while typing a word (expected: only shows up after moving away from word)
2. Typing on the same line with mis-spelled words causes their underlines to flash.

In Safari:
1. Underlines don't always show up. Seems like hitting enter after a word or clicking in the middle of a word and then else where will cause them to show up.
2. Underlines disappear when typing on same line.

**Comment by marijnh** [comment]
This is due to the fact that ProseMirror makes and renders the changes to the document, instead of letting user events through, and it is probably unavoidable for an editor built with this architecture (until browser decide to give scripts control over spell-checking -- but don't hold your breath for that one /cc @johanneswilm).

**Comment by johanneswilm** [comment]
@marijnh What we will get is a beforeinput event that gives a target range specifying what the user asked to be changed and what the replacement word would be.

What there is opposition to among some browser vendors is to give scripts direct access to the spell checker functionality. This is because at least Safari uses the system dictionary which can have custom entries which could give clues about the user. So it ends up being a privacy issue.

We have talked a bit about what other options would be available. One could be that one can mark certain regions as being in need of spell checking or mark a range as having been checked already. If you guys have ideas  about that, feel free to share them.

**Comment by wes-r** [comment]
So the issue is that ProseMirror is disrupting the normal flow of user events within contenteditable? Is it possible to not have it do this for normal character insertion?

If there's no good way to get the default spell checker working then ProseMirror should probably come with spell check disabled by default and with a comment about default spell checking not working.

Anyone know of any good JS spell checkers? I was most likely going to need to go down this path anyway in order to allow for a custom contextmenu (like google docs).

**Comment by marijnh** [comment]
I think the behavior you describe is not _broken_ per se -- it does allow users to use the spell checker, it's just a bit more aggressive about underlining than usual.

**Comment by wes-r** [comment]
Maybe in chrome but not in safari as the underlines don't always appear.

**Comment by johanneswilm** [comment]
> Anyone know of any good JS spell checkers?

The main problem with this is download size of the dictionaries. This problem will (obviously) solve itself with time, but for the time being downloading 1-10MB is still not something most will want their website visitors to go through.

The alternative is using webservices -- but those are either paid for, or you run it yourself and will mean you need to calculate that in when figuring out what kind of server you need.

**Comment by johanneswilm** [comment]
Looks like the US English dictionary here is about 700kb: http://www.chrisfinke.com/files/typo-demo/ . That may be acceptable under some circumstances, especially if it's cached.

I think another thing that browser makers may be convinced of, if they accept that this a big enough issue for users, could be to allow for access to systems dictionaries without modifications -- in other words, the dictionaries as they are shipped with the OS without anything they user may have added or edited.

**Comment by wes-r** [comment]
Sounds like due to the way ProseMirror works this is sort of a **WONTFIX/CANTFIX** and there's now an option to disable default spell check.

Closing.

P.S: The mark range system is perfect for do it yourself spell checking as you can mark a range with a className that adds the underlines!

**Comment by rafbm** [comment]
I am very interested in the development of ProseMirror. I have been comparing it closely with other modern libraries and truly think it has the best foundation to become the most powerful editor out there. However right now it falls short from a UX perspective, preventing spellcheck in Safari and acting unexpectedly on iOS, see #463 and #234 (double-tap space issue is closed but hasn’t actually been fixed in PM itself).

Here is a visual example of the current Safari behavior with a spellcheck-enabled ProseMirror:

![prosemirror](https://cloud.githubusercontent.com/assets/166943/19796043/66661b70-9caf-11e6-8975-8cb91ee13df1.gif)

The problem is pretty obvious. @marijnh’s position on the matter (emphasis mine):

> This is due to the fact that ProseMirror makes and renders the changes to the document, instead of letting user events through, and _it is probably unavoidable for an editor built with this architecture_

I think it’s worth showing how seamless the Safari spellcheck experience is with [Trix](https://trix-editor.org/):

![trix](https://cloud.githubusercontent.com/assets/166943/19796931/c6388ffa-9cb5-11e6-80b8-1802cd4f80cf.gif)

Though I have yet to dig in the internals of ProseMirror and Trix to see exactly how each updates their view, the DOM tree highlights that appear in the Chrome console seem to indicate that ProseMirror replaces full `<span>` elements whereas Trix updates text nodes directly.

Considering this, plus the fact that Trix _does_ use an architecture where all key events are intercepted, applied on a document model and re-rendered into the DOM (see text in GIF above), there must be a way for ProseMirror to update text nodes directly and be on par with Trix regarding spellcheck and iOS behavior [without](https://github.com/ProseMirror/prosemirror/commit/7b6bdd1846fecc92e8e060d39b5a457abb73c6ea) any [hack](https://github.com/ProseMirror/prosemirror/commit/eee5c4cbd47fb1a2d95d49392401b24234eb21de).

I would love to have Marijnh’s thoughts on this. Is there really some core principle to ProseMirror that would prevent adopting this approach?

Note that [Quill](http://quilljs.com/) and [Draft.js](https://facebook.github.io/draft-js/) also provide the exact same Safari behavior as Trix.

**Comment by marijnh** [comment]
Given your analysis, it appears that browser react much better to text nodes being updated than to whole spans being replaced, when it comes to spell-checking behavior. That is hopeful. We could experiment with using something like [incremental-dom](https://github.com/google/incremental-dom) or our own reduced implementation to do the actual rewriting of DOM nodes, and see if that makes things better. I'm reopening this issue to further track that work.

**Comment by marijnh** [comment]
> Though I have yet to dig in the internals of ProseMirror and Trix to see exactly how each updates their view, the DOM tree highlights that appear in the Chrome console seem to indicate that ProseMirror replaces full <span> elements whereas Trix updates text nodes directly.

@rafbm In the next release, ProseMirror will also use an update model where it directly updates text nodes (by setting their `nodeValue`), but unfortunately, this _does not help_ at all in Safari, where you still don't get spell-checking underlines until you move the cursor. If you want to do more research into what Trix & co are actually doing, that might be useful.

**Comment by marijnh** [comment]
For those interested, here's the most minimal update-dom-directly-on-keypress editor implementation I could come up with. In Safari, this suppresses all spell checking, so I suspect that the editors in which spell check works are letting keypress events go through after all.

```html
<!doctype html>
<meta charset=utf8>

<div style="border: 1px solid silver; padding: 5px; white-space: pre-wrap" contenteditable=true><p>hello</p></div>

<script>
  function setSel(node, offset) {
    let s = getSelection(), r = document.createRange()
    r.setEnd(node, offset)
    r.collapse(false)
    s.removeAllRanges()
    s.addRange(r)
  }

  document.querySelector("div").addEventListener("keypress", e => {
    e.preventDefault()
    let s = getSelection(), node = s.focusNode
    if (node.nodeType == 3) {
      let offset = s.focusOffset
      node.nodeValue = node.nodeValue.slice(0, offset) + String.fromCharCode(e.charCode) +
        node.nodeValue.slice(offset)
      setSel(node, offset + 1)
    }
  })
</script>
```

**Comment by rafbm** [comment]
You are totally right Marijn. Sorry for providing a incorrect analysis in the first place.

> Considering this, plus the fact that Trix does use an architecture where all key events are intercepted, applied on a document model and re-rendered into the DOM […]

It appears this is actually _not true for simple character inputs_. Other editors (see [Trix](https://github.com/basecamp/trix/blob/59d14822c2ffa0e846334c70d637f8ce52c55e7d/src/trix/observers/mutation_observer.coffee#L15) and [Quill](https://github.com/quilljs/parchment/blob/ff9b6f1f54c0ad457968df1f396bab5fdeac7c89/src/blot/scroll.ts#L29)) are using a [MutationObserver](http://caniuse.com/#feat=mutationobserver) (with polyfill via [Mutation Events](http://caniuse.com/#feat=mutation-events) for IE9-10). In Trix’s case, it’s simple to see they [catch `childList` and `characterData`-type mutations](https://github.com/basecamp/trix/blob/59d14822c2ffa0e846334c70d637f8ce52c55e7d/src/trix/observers/mutation_observer.coffee#L84-L118), such as this example where I typed “g” at the end of a node:

<img width="289" alt="screen shot 2016-11-28 at 07 51 24" src="https://cloud.githubusercontent.com/assets/166943/20669093/37c94d92-b540-11e6-9baf-ea36ebb22709.png">

Trix then [compares the MutationRecord’s `oldValue`](https://github.com/basecamp/trix/blob/59d14822c2ffa0e846334c70d637f8ce52c55e7d/src/trix/observers/mutation_observer.coffee#L113-L115) with a [simple diffing algorithm](https://github.com/basecamp/trix/blob/759e62d5846b5d59cdd6174fae6027ce984752aa/src/trix/core/helpers/strings.coffee#L7-L46), which they use to update their internal document model, without any further change to the DOM beside the original, un-prevented keypress/input event.

That seems to be the only way to get spell check as they do in Safari, however I was also wrong stating that Trix provides a “_seamless_ spell check behavior in Safari”. With just a little more testing, it’s clear that whenever they do need to prevent default events and apply them programatically, Safari’s pickiness kicks in and you lose spell check underlines you had:

![trix](https://cloud.githubusercontent.com/assets/166943/20669291/69743ea0-b541-11e6-8c3e-f0c561d1b680.gif)

For anything beyond simple character input (here inserting a `<strong>` and appending a `<br>`), Trix replaces the whole node content and the spell check experience is hurt.

So I guess having truly seamless spell check in Safari may be a pipe dream. However I do believe their MutationObserver strategy where keypress/input events are not prevented on simple character input is what makes Trix smoother on iOS.

**Comment by marijnh** [comment]
> With just a little more testing, it’s clear that whenever they do need to prevent default events and apply them programatically, Safari’s pickiness kicks in and you lose spell check underlines you had

Yeah, I was about to say something similar. ProseMirror could, at the cost of some efficiency (parsing, diffing, and fixing up the DOM is a bunch of work), let plain keypress events through, but there are _many_ situations where it will have to touch the DOM, which seems to cause Safari's spell checker to immediately run and hide. So the experience could be a little better, but it'll be relatively poor still. If you want, I can provide this behavior (ignoring keypress) as an option.

**Comment by rafbm** [comment]
I think letting `keypress` / `input` events go through would be a big benefit for all users. Having this be the default behavior rather than an option would make sense to me.

While it’s definitely OK to consider Safari a lost cause, doing some further testing on a spellcheck-enabled ProseMirror in Chrome shows that the experience is almost worst than without spell check. Since text nodes are fully rewritten, underlines appear while typing partial words (before hitting Space) and always keep flashing on every further keystroke:

![underlines](https://cloud.githubusercontent.com/assets/166943/20732881/ce3919a0-b65e-11e6-8620-4c3c9e3d9229.gif)

The above is latest ProseMirror on http://prosemirror.net/ with the `spellcheck="false"` attribute manually removed.

This, as well as most iOS issues if I’m not mistaken, sound like a good reason to explore a strategy similar to Trix / Quill for simple character inputs.

**Comment by marijnh** [comment]
Letting keys go through won't, by itself, do anything about the flashing, and we're _already_ letting keypress through on iOS.

**Comment by marijnh** [comment]
I've pushed a bunch of patches (e47c3b6e4ec5...448dee780) that takes a hint from Trix and uses `MutationObserver` (which I had started with but given up on, but which is viable again with ProseMirror's current DOM management technique) to get a more precise and reliable view on which DOM nodes changed. This has made letting the browser handle typing and backspacing (when not across block boundaries) viable and relatively efficient again. I've come up with a way to have simple editing, when the browser's behavior agree with what ProseMirror would have done, happen with zero programmatic redraws, so that should make Safari spell check kinda work. It still resets as soon as you add a mark or do something similar, but it's better than it was before.

I think this is about as far as we can go with this. We do, in the end, need control over marks, and our model of marks is completely different from the browser's `execCommand` approach. It might be possible to cover some cases with hacky uses of `execCommand`, but that'd still be only partial, and introduce a lot of complexity that's probably not worth it. So I'm closing this, but feel free to continue discussing or to open new issues for related problems.

**Comment by johanneswilm** [comment]
> It might be possible to cover some cases with hacky uses of execCommand, but that'd still be only partial, and introduce a lot of complexity that's probably not worth it. 

Yes, please do not start using execCommand. ExecCommand will likely be gone in future versions of contenteditable, so this is not an area I would recommend adding dependencies in.

**Comment by rafbm** [comment]
Thanks very much for efforts in this direction Marijn! It does seem to be as far as we can go without adding unwanted complexity. It’s also very nice to see pretty much all `if (browser.ios)` conditions removed. Fewer code branches, fewer bugs!

I’m stumbling on a few core bugs while fiddling with the demo. I pulled all latest versions of the repos and removed all content from the initial node:

```html
<div id=content style="display: none"></div>
```

On the first line, Backspace does nothing at all. On the lines after, it *deletes the whole line*, rather than a single character. And the cursor gets moved to the *beginning of the previous line*.

![backspace-3](https://cloud.githubusercontent.com/assets/166943/20931867/9c60729c-bba0-11e6-93bd-dbd4ee1c617f.gif)

**Comment by rafbm** [comment]
And here’s an exception that gets thrown (probably an edge case). It’s when I backspace the apostrophe after the browser replaced it from `'` to `’`:

![backspace-4](https://cloud.githubusercontent.com/assets/166943/20932913/4bcb6356-bba4-11e6-8200-a696bd5d3fe6.gif)

**Comment by wes-r** [comment]
Working on upgrading from 0.12 to 0.14 and am running into the same things @rafbm ran into.

**Comment by rafbm** [comment]
Other buggish behavior here. I’m doing Alt+Fn+Backspace (ie. Alt+Delete) to forward-delete words. The first 3 times (inside sentence) it works, but then doing so before the hard break of the first line, it duplicates the content of the next line.

![alt-delete](https://cloud.githubusercontent.com/assets/166943/20937569/832d4ef2-bbb5-11e6-945c-25e99b1ef9b6.gif)

I’m reporting all these bugs because they look different, but let me know if you’re already implementing a magic fix for all of them. I’ll stop with the GIFs. :)

**Comment by marijnh** [comment]
> Working on upgrading from 0.12 to 0.14 and am running into the same things @rafbm ran into.

None of this has been released so probably you're seeing a different problem.

**Comment by marijnh** [comment]
I've pushed some patches that seem to fix the issues you found, @rafbm . Please open new issues for further problems, so that we don't make a mess of this issue.

**Comment by mitar** [comment]
Just one additional idea here, which I think is closer to what Google Docs does: do spell-checking on the server. So at least in collaborative editing scenario, I am already sending every change to the server. Server could do its regular state update, then extract text, do spell checking, if anything is bad, use marks to mark that as failing spell checking, add one more version, and send both original version and additional version with spell checking back to all users. This would have an added benefit that all users would see regions of the document with failed spell checking, and even have per-document or per-project exceptions (custom dictionary).
